using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI.WebControls;

namespace Mediqura.Web.MedCommon
{
    public class Messagealert_
    {
        public static void ShowMessage(Label lbl, string message, int msgType)
        {

            message = message.ToString().Trim() == "system" ? "System could not process your request, please try again." : message;
            message = message.ToString().Trim() == "save" ? "Saved Successfully." : message;
            message = message.ToString().Trim() == "cancel" ? "Cancelled Successfully." : message;
            message = message.ToString().Trim() == "verify" ? "Verified Successfully." : message;
            message = message.ToString().Trim() == "verifyby" ? "Please select verify by." : message;
            message = message.ToString().Trim() == "ReqdQty" ? "Please enter the required item quantity." : message;
            message = message.ToString().Trim() == "ApprovedQty" ? "Please enter approved quantity." : message;
            message = message.ToString().Trim() == "TransferQty" ? "Please enter transfer quantity." : message;
            message = message.ToString().Trim() == "send" ? "Sent for approval successfully." : message;
            message = message.ToString().Trim() == "generate" ? "PO generated successfully." : message;
            message = message.ToString().Trim() == "ValidDate" ? "Please enter a valid date." : message;
            message = message.ToString().Trim() == "DOB" ? "Please enter date of birth." : message;
            message = message.ToString().Trim() == "RecivedDate" ? "Please enter received date." : message;
            message = message.ToString().Trim() == "MfgDate" ? "Please enter manufacturing date." : message;
            message = message.ToString().Trim() == "ExpirDate" ? "Please enter expiry date." : message;
            message = message.ToString().Trim() == "ValidDatefrom" ? "Please enter valid date from." : message;
            message = message.ToString().Trim() == "ValidDateto" ? "Please enter valid date to." : message;
            message = message.ToString().Trim() == "PatientType" ? "Please select patient type." : message;
            message = message.ToString().Trim() == "Email" ? "Please enter valid email id." : message;
            message = message.ToString().Trim() == "Pin" ? "Please enter a valid PIN." : message;
            message = message.ToString().Trim() == "Template" ? "Please enter template." : message;
            message = message.ToString().Trim() == "mobile" ? "Please enter a valid mobile number." : message;
            message = message.ToString().Trim() == "DupConsulatation" ? "Already created." : message;
            message = message.ToString().Trim() == "emergencymobile" ? "Please enter a valid emergency contact number." : message;
            message = message.ToString().Trim() == "standardtime" ? "Please enter standard time in minutes." : message;
            message = message.ToString().Trim() == "SaveEnable" ? "You do not have the rights to save data." : message;
            message = message.ToString().Trim() == "UpdateEnable" ? "You do not have the rights to update data." : message;
            message = message.ToString().Trim() == "SearchEnable" ? "You do not have the rights to search data." : message;
            message = message.ToString().Trim() == "ExportEnable" ? "You do not have the rights to export data." : message;
            message = message.ToString().Trim() == "DeleteEnable" ? "You do not have the rights to delete data." : message;
            message = message.ToString().Trim() == "EditEnable" ? "You do not have the rights to edit data." : message;
            message = message.ToString().Trim() == "PrintEnable" ? "You do not have the rights to print data." : message;
            message = message.ToString().Trim() == "update" ? "Updated successfully." : message;
            message = message.ToString().Trim() == "return" ? "Returned successfully." : message;
            message = message.ToString().Trim() == "Error" ? "Could not be updated successfully." : message;
            message = message.ToString().Trim() == "delete" ? "Deleted successfully." : message;
            message = message.ToString().Trim() == "BlankPassword" ? "Please enter password." : message;
            message = message.ToString().Trim() == "Password" ? "Please enter the correct password." : message;
            message = message.ToString().Trim() == "Remarks" ? "Please enter remarks." : message;
            message = message.ToString().Trim() == "ExportType" ? "Please select export type." : message;
            message = message.ToString().Trim() == "Exported" ? "Exported successfully." : message;
            message = message.ToString().Trim() == "DateRange" ? "Please select a date range." : message;
            message = message.ToString().Trim() == "Email" ? "Please enter a valid email id." : message;
            message = message.ToString().Trim() == "duplicate" ? "Already exist." : message;
            message = message.ToString().Trim() == "Refund" ? "Successfully refunded." : message;
            message = message.ToString().Trim() == "UserNameError" ? "Please enter the correct username." : message;
            message = message.ToString().Trim() == "PasswordError" ? "Old password does not match with database record." : message;
            message = message.ToString().Trim() == "PswdStrongType" ? "Password must be minimum of 5 characters." : message;
            message = message.ToString().Trim() == "ConfirmedPswd" ? "Password does not match." : message;
            message = message.ToString().Trim() == "DiscountOver" ? "Discount amount should not be greater than paid amount." : message;
            message = message.ToString().Trim() == "Total" ? "Sum of each charges should not be greater than total charge." : message;
            message = message.ToString().Trim() == "statusUpdate" ? "Sample is already collected. Refund not elligible." : message;
            message = message.ToString().Trim() == "status" ? "Sample is already collected." : message;
            message = message.ToString().Trim() == "Method" ? "Please enter method name." : message;
            message = message.ToString().Trim() == "ServiceType" ? "Please select service type." : message;
            message = message.ToString().Trim() == "DoctorType" ? "Please select doctor type." : message;
            message = message.ToString().Trim() == "Doctor" ? "Please select doctor." : message;
            message = message.ToString().Trim() == "Department" ? "Please select department." : message;
            message = message.ToString().Trim() == "Service" ? "Please enter service." : message;
            message = message.ToString().Trim() == "DoctorName" ? "Please enter doctor's name." : message;
            message = message.ToString().Trim() == "Tax" ? "Please enter tax." : message;
            message = message.ToString().Trim() == "Commission" ? "Please enter commission." : message;
            message = message.ToString().Trim() == "CommissionCheck" ? "Commission cannot be greater than service charge." : message;
            message = message.ToString().Trim() == "Consultant" ? "Please select consultant." : message;
            message = message.ToString().Trim() == "Charge" ? "Please enter charge." : message;
            message = message.ToString().Trim() == "Listcheck" ? "Already added to the list." : message;
            message = message.ToString().Trim() == "UHID" ? "Please enter UHID." : message;
            message = message.ToString().Trim() == "Paymode" ? "Please select payment mode." : message;
            message = message.ToString().Trim() == "Totalamount" ? "Please enter total amount." : message;
            message = message.ToString().Trim() == "BankName" ? "Please enter the bank name." : message;
            message = message.ToString().Trim() == "Reagent" ? "Please enter the reagent name." : message;
            message = message.ToString().Trim() == "ReagentType" ? "Please select the reagent type." : message;
            message = message.ToString().Trim() == "Account" ? "Please enter the account number." : message;
            message = message.ToString().Trim() == "DiscountBy" ? "Please enter discount by." : message;
            message = message.ToString().Trim() == "DiscountByselect" ? "Please select discount by and enter remarks." : message;
            message = message.ToString().Trim() == "VaildDatefrom" ? "Please enter a vaild date from." : message;
            message = message.ToString().Trim() == "VaildDateto" ? "Please enter a vaild date to." : message;
            message = message.ToString().Trim() == "Tax" ? "Please enter tax rate." : message;
            message = message.ToString().Trim() == "Quantity" ? "Please enter quantity." : message;
            message = message.ToString().Trim() == "FreeQuantity" ? "Please enter free quantity." : message;
            message = message.ToString().Trim() == "CP" ? "Please enter cost price." : message;
            message = message.ToString().Trim() == "MRP" ? "Please enter total MRP." : message;
            message = message.ToString().Trim() == "RCNO" ? "Please enter receipt number." : message;
            message = message.ToString().Trim() == "ItemName" ? "Please enter item name." : message;
            message = message.ToString().Trim() == "BatchNo" ? "Please enter batch number." : message;
            message = message.ToString().Trim() == "Referal" ? "Please enter referal." : message;
            message = message.ToString().Trim() == "ConsultattionBill" ? "Hi, today there is no billing for your OPD consultation." : message;
            message = message.ToString().Trim() == "BlankSchedule" ? "Please enter atleast one of the slots." : message;
            message = message.ToString().Trim() == "Height" ? "Please enter height." : message;
            message = message.ToString().Trim() == "Weight" ? "Please enter weight." : message;
            message = message.ToString().Trim() == "BP" ? "Please enter BP." : message;
            message = message.ToString().Trim() == "Pulse" ? "Please enter pulse rate." : message;
            message = message.ToString().Trim() == "Billno" ? "Please enter bill number." : message;
            message = message.ToString().Trim() == "checkbox" ? "No item selected!" : message;
            message = message.ToString().Trim() == "payment" ? "Payment amount cannot exceeds payable amount." : message;
            message = message.ToString().Trim() == "validAmount" ? "please enter a valid amount." : message;
            message = message.ToString().Trim() == "Purchagetype" ? "Please select purchase  type." : message;
            message = message.ToString().Trim() == "PO" ? "Please enter PO number." : message;
            message = message.ToString().Trim() == "tpa" ? "Please enter tpa description." : message;
            message = message.ToString().Trim() == "Group" ? "Please select group." : message;
            message = message.ToString().Trim() == "mfgcompany" ? "Please enter manufacturing company." : message;
            message = message.ToString().Trim() == "supplier" ? "Please enter supplier." : message;
            message = message.ToString().Trim() == "Nounit" ? "Please enter number unit." : message;
            message = message.ToString().Trim() == "Unitperqty" ? "Please enter number quantity per unit." : message;
            message = message.ToString().Trim() == "Costprice" ? "Please enter total cost price." : message;
            message = message.ToString().Trim() == "Recievedby" ? "Please select received by." : message;
            message = message.ToString().Trim() == "NurseType" ? "Please select nurse type." : message;
            message = message.ToString().Trim() == "nursetype" ? "Please enter nurse type." : message;
            message = message.ToString().Trim() == "Nurse" ? "Please enter nurse." : message;
            message = message.ToString().Trim() == "StockistDiscount" ? "Discount amount is greater than the actual cost amount." : message;
            message = message.ToString().Trim() == "Issueto" ? "Please enter issue to." : message;
            message = message.ToString().Trim() == "Subgroup" ? "Please select sub group." : message;
            message = message.ToString().Trim() == "Handedto" ? "Please select handed to." : message;
            message = message.ToString().Trim() == "ItemCount" ? "Please enter at least one item." : message;
            message = message.ToString().Trim() == "IndentNo" ? "Please enter indent number." : message;
            message = message.ToString().Trim() == "Week" ? "Please select week." : message;
            message = message.ToString().Trim() == "Doctor" ? "Please select doctor." : message;
            message = message.ToString().Trim() == "IssueQty" ? "Issue quantity is greater than available qunatity." : message;
            message = message.ToString().Trim() == "GReturnQty" ? "Return quantity is greater than available qunatity." : message;
            message = message.ToString().Trim() == "StockType" ? "Please select stock type." : message;
            message = message.ToString().Trim() == "ReturnQty" ? "Please enter return quantity." : message;
            message = message.ToString().Trim() == "patientname" ? "Please enter patient name." : message;
            message = message.ToString().Trim() == "PatientAddress" ? "Please enter patient address." : message;
            message = message.ToString().Trim() == "ZeroQty" ? "Please enter quantity to issue." : message;
            message = message.ToString().Trim() == "Checked" ? "Please select items to be approved." : message;
            message = message.ToString().Trim() == "CheckedPO" ? "The given PO is already checked." : message;
            message = message.ToString().Trim() == "Block" ? "Please select block." : message;
            message = message.ToString().Trim() == "AdmissionDoctor" ? "Please select admission doctor." : message;
            message = message.ToString().Trim() == "Floor" ? "Please select floor." : message;
            message = message.ToString().Trim() == "Ward" ? "Please select ward." : message;
            message = message.ToString().Trim() == "Code" ? "Please enter code." : message;
            message = message.ToString().Trim() == "Bedno" ? "Please select only one bed." : message;
            message = message.ToString().Trim() == "NurseCharge" ? "Please enter nurse service charge." : message;
            message = message.ToString().Trim() == "BlockType" ? "Please select block type." : message;
            message = message.ToString().Trim() == "dept" ? "Please enter department." : message;
            message = message.ToString().Trim() == "Department" ? "Please select department." : message;
            message = message.ToString().Trim() == "Designation" ? "Please enter designation." : message;
            message = message.ToString().Trim() == "FloorType" ? "Please enter floor." : message;
            message = message.ToString().Trim() == "HospitalName" ? "Please enter hospital name." : message;
            message = message.ToString().Trim() == "HospitalAddress" ? "Please enter hospital address." : message;
            message = message.ToString().Trim() == "Country" ? "Please select country." : message;
            message = message.ToString().Trim() == "State" ? "Please select state." : message;
            message = message.ToString().Trim() == "Website" ? "Please enter website." : message;
            message = message.ToString().Trim() == "Email" ? "Please enter email id." : message;
            message = message.ToString().Trim() == "RecogNo" ? "Please enter recognition number." : message;
            message = message.ToString().Trim() == "PhoneNo" ? "Please enter phone number." : message;
            message = message.ToString().Trim() == "MobileNo" ? "Please enter mobile number." : message;
            message = message.ToString().Trim() == "FaxNo" ? "Please enter fax number." : message;
            message = message.ToString().Trim() == "CustomerType" ? "Please select patient type." : message;
            message = message.ToString().Trim() == "Custommer" ? "Please enter custommer name." : message;
            message = message.ToString().Trim() == "Address" ? "Please enter customer address." : message;
            message = message.ToString().Trim() == "ReturnQty" ? "Please enter true return quantity." : message;
            message = message.ToString().Trim() == "VaildPC" ? "Please enter correct percentage to deduct." : message;
            message = message.ToString().Trim() == "ReceivedBy" ? "Please enter received by." : message;
            message = message.ToString().Trim() == "CountReturn" ? "Please enter atleast one return quantity." : message;
            message = message.ToString().Trim() == "Year" ? "Please select year." : message;
            message = message.ToString().Trim() == "CondQty" ? "Please enter atleast one condemn quantity to update." : message;
            message = message.ToString().Trim() == "ExpireStart" ? "Please enter number of days from which the item  is near to death." : message;
            message = message.ToString().Trim() == "ExpireEnd" ? "Please enter number of days from which the item will be block." : message;
            message = message.ToString().Trim() == "Daycounterror" ? "Please enter the correct day count." : message;
            message = message.ToString().Trim() == "Case" ? "Please enter case." : message;
            message = message.ToString().Trim() == "GroupType" ? "Please enter group." : message;
            message = message.ToString().Trim() == "TestName" ? "Please select test." : message;
            message = message.ToString().Trim() == "LabTestName" ? "Please enetr test." : message;
            message = message.ToString().Trim() == "TestCenter" ? "Please select testcenter." : message;
            message = message.ToString().Trim() == "PaymentType" ? "Please select paymenttype." : message;
            message = message.ToString().Trim() == "Unit" ? "Please enter units." : message;
            message = message.ToString().Trim() == "SUnit" ? "Please select units." : message;
            message = message.ToString().Trim() == "Age" ? "Please enter age." : message;
            message = message.ToString().Trim() == "AgeRange" ? "Please enter age range." : message;
            message = message.ToString().Trim() == "Machine" ? "Please enter machine name." : message;
            message = message.ToString().Trim() == "MachineName" ? "Please select machine name." : message;
            message = message.ToString().Trim() == "LabID" ? "Please enter lab id." : message;
            message = message.ToString().Trim() == "takenBY" ? "Please select collected by." : message;
            message = message.ToString().Trim() == "Sample" ? "Please enter sample." : message;
            message = message.ToString().Trim() == "SubgroupType" ? "Please enter sub group type." : message;
            message = message.ToString().Trim() == "CenterName" ? "Please enter center name." : message;
            message = message.ToString().Trim() == "Patient" ? "Please enter patient type." : message;
            message = message.ToString().Trim() == "PaymentType" ? "Please enter payment type." : message;
            message = message.ToString().Trim() == "ReferalDoctor" ? "Please enter referral doctor." : message;
            message = message.ToString().Trim() == "StockType" ? "Please enter stock type." : message;
            message = message.ToString().Trim() == "FloorType" ? "Please enter floor type." : message;
            message = message.ToString().Trim() == "Company" ? "Please enter company name." : message;
            message = message.ToString().Trim() == "TestName" ? "Please enter test name." : message;
            message = message.ToString().Trim() == "Description" ? "Please enter description." : message;
            message = message.ToString().Trim() == "Testname" ? "Please enter test name." : message;
            message = message.ToString().Trim() == "Unit" ? "Please enter unit." : message;
            message = message.ToString().Trim() == "Age" ? "Please enter age." : message;
            message = message.ToString().Trim() == "Range" ? "Please enter age range." : message;
            message = message.ToString().Trim() == "Gender" ? "Please select gender." : message;
            message = message.ToString().Trim() == "IPNo" ? "Please enter IP number." : message;
            message = message.ToString().Trim() == "surgeon" ? "Please enter surgeon." : message;
            message = message.ToString().Trim() == "AsstSurgeon" ? "Please enter assistant surgeon." : message;
            message = message.ToString().Trim() == "Operationdate" ? "Please enter operation date correctly." : message;
            message = message.ToString().Trim() == "BedTransfer" ? "Please check atleast one bed to transfer." : message;
            message = message.ToString().Trim() == "AdmissionStatus" ? "Already done the admission for this UHID. Please discharge and do the admission process again." : message;
            message = message.ToString().Trim() == "bedtransfer" ? "Successfully transfered." : message;
            message = message.ToString().Trim() == "OTtheater" ? "Please select operation theater." : message;
            message = message.ToString().Trim() == "OTcase" ? "Please select case." : message;
            message = message.ToString().Trim() == "OTrole" ? "Please enter ot roles." : message;
            message = message.ToString().Trim() == "OTemployee" ? "Please select OT employee." : message;
            message = message.ToString().Trim() == "OTintimatedby" ? "Please select intimation by." : message;
            message = message.ToString().Trim() == "Discount" ? "Please enter discount amount." : message;
            message = message.ToString().Trim() == "CrossChecked" ? "The given PO number is already cross checked." : message;
            message = message.ToString().Trim() == "Transfer" ? "Please select stock from." : message;
            message = message.ToString().Trim() == "Testnames" ? "Please select test name." : message;
            message = message.ToString().Trim() == "Male" ? "Please enter normal range for male." : message;
            message = message.ToString().Trim() == "Female" ? "Please enter normal range for female." : message;
            message = message.ToString().Trim() == "Children" ? "Please enter normal range for children." : message;
            message = message.ToString().Trim() == "categoryrange" ? "Please enter code category range." : message;
            message = message.ToString().Trim() == "company" ? "Please select company." : message;
            message = message.ToString().Trim() == "package" ? "Please select package." : message;
            message = message.ToString().Trim() == "IssueDate" ? "Please enter select issue date." : message;
            message = message.ToString().Trim() == "empname" ? "Please enter employee name." : message;
            message = message.ToString().Trim() == "SelectPatient" ? "Please select a patient first." : message;
            message = message.ToString().Trim() == "Substock" ? "Please select a sub-stock" : message;
            message = message.ToString().Trim() == "Approved" ? "Can't delete Indent.Indent is already approved." : message;
            message = message.ToString().Trim() == "HandOver" ? "Can't delete Indent.Indent is already handOver." : message;
            message = message.ToString().Trim() == "Received" ? "Can't delete Indent.Indent is already received." : message;
            message = message.ToString().Trim() == "ApproveQty" ? "Approved quantity can't be greater than request qty." : message;
            message = message.ToString().Trim() == "HndOvQty" ? "Handover quantity can't be greater than approved qty." : message;
            message = message.ToString().Trim() == "ReqQty" ? "Please enter request quantity." : message;
            message = message.ToString().Trim() == "HndOv" ? "Please enter request handover quantity." : message;
            message = message.ToString().Trim() == "RecvQty" ? "Please enter request handover quantity." : message;
            message = message.ToString().Trim() == "ReceivedQty" ? "Please enter received quantity." : message;
            message = message.ToString().Trim() == "AccountGroupUnder" ? "Please select account group under." : message;
            message = message.ToString().Trim() == "AccountGroupName" ? "Please enter account group name." : message;
            message = message.ToString().Trim() == "AccountGroupNature" ? "Please select account group nature." : message;
            message = message.ToString().Trim() == "RequestType" ? "Please select a request type." : message;
            message = message.ToString().Trim() == "ReqQtyNo" ? "Request quantity can't be greater than available qty" : message;
            message = message.ToString().Trim() == "ReqSentEnable" ? "You do not have rights to send indent." : message;
            message = message.ToString().Trim() == "Share" ? "Total share can't be greater than rate" : message;
            message = message.ToString().Trim() == "PC" ? "Please enter correct percentage." : message;
            message = message.ToString().Trim() == "BedClass" ? "Please select bed class." : message;
            message = message.ToString().Trim() == "ShareType" ? "Please select share type." : message;
            message = message.ToString().Trim() == "AccountSite" ? "Please enter account site details." : message;
            message = message.ToString().Trim() == "AccountOpeningBalance" ? "Please enter account opening balance." : message;
            message = message.ToString().Trim() == "AccountOpeningDate" ? "Please enter account opening date." : message;
            message = message.ToString().Trim() == "HandOverBy" ? "Please select handOver to." : message;
            message = message.ToString().Trim() == "ApprvBy" ? "Please select approved by." : message;
            message = message.ToString().Trim() == "PaymentType" ? "Please select payment type." : message;
            message = message.ToString().Trim() == "PaymentMode" ? "Please select payment Mode." : message;
            message = message.ToString().Trim() == "PaymentDate" ? "Please enter payment Date." : message;
            message = message.ToString().Trim() == "DebitLedger" ? "Please enter a debit account." : message;
            message = message.ToString().Trim() == "DebitAmount" ? "Please enter a debit amount." : message;
            message = message.ToString().Trim() == "CreditAmount" ? "Please enter a credit amount." : message;
            message = message.ToString().Trim() == "CreditLedger" ? "Please enter a credit account." : message;
            message = message.ToString().Trim() == "TransactionType" ? "Please select a transaction type." : message;
            message = message.ToString().Trim() == "InstrumentName" ? "Please enter instrument name." : message;
            message = message.ToString().Trim() == "InstrumentDate" ? "Please enter instrument date." : message;
            message = message.ToString().Trim() == "BankPayee" ? "Please enter bank payee name." : message;
            message = message.ToString().Trim() == "BankBranch" ? "Please enter bank branch." : message;
            message = message.ToString().Trim() == "AccountNarration" ? "Please enter account narration." : message;
            message = message.ToString().Trim() == "EmergencyDoctor" ? "Please select emergency doctor." : message;
            message = message.ToString().Trim() == "EMRGNO" ? "Please enter emergency number." : message;
            message = message.ToString().Trim() == "dependentNo" ? "Please enter number of dependent." : message;
            message = message.ToString().Trim() == "MaritalStatus" ? "Please select marital status." : message;
            message = message.ToString().Trim() == "RelationShip" ? "Please enter dependent relationship." : message;
            message = message.ToString().Trim() == "msbOPD" ? "Please enter OPD value." : message;
            message = message.ToString().Trim() == "msbInvestigation" ? "Please enter investigation value." : message;
            message = message.ToString().Trim() == "msbEMP" ? "Please enter MSB employee name." : message;
            message = message.ToString().Trim() == "msbDependent" ? "Please enter dependent UHID." : message;
            message = message.ToString().Trim() == "MsbRelation" ? "Please selection dependent relationship with the employee" : message;
            message = message.ToString().Trim() == "MsbIncome" ? "Please enter dependent income." : message;
            message = message.ToString().Trim() == "MsbApplydate" ? "Please enter apply date." : message;
            message = message.ToString().Trim() == "MsbIssueDate" ? "Please enter issue date" : message;
            message = message.ToString().Trim() == "MsbValidDate" ? "Please enter valid date" : message;
            message = message.ToString().Trim() == "MsbRemarks" ? "Please enter remarks" : message;
            message = message.ToString().Trim() == "MsbSpecial" ? "The dependent is not eligible." : message;
            message = message.ToString().Trim() == "MsbOccupation" ? "Please enter dependent occupation." : message;
            message = message.ToString().Trim() == "MsbDuplicate" ? "Dependent already exist." : message;
            message = message.ToString().Trim() == "EmpGrade" ? "Select employee grade." : message;
            message = message.ToString().Trim() == "Percentage" ? "Percentage cannot exceed 100% !" : message;
            message = message.ToString().Trim() == "DiscountAmount" ? "Discount amount cannot exceed net amount!" : message;
            message = message.ToString().Trim() == "DischargeType" ? "Please select discharge Type" : message;
            message = message.ToString().Trim() == "DiscountReq" ? "Discount request sent!" : message;
            message = message.ToString().Trim() == "DiscountDuplicate" ? "Request already process!" : message;
            message = message.ToString().Trim() == "Paracount" ? "Please add atleast one parameter." : message;
            message = message.ToString().Trim() == "LabReportType" ? "Please select report type." : message;
            message = message.ToString().Trim() == "InvNo" ? "Please enter investigation number." : message;
            message = message.ToString().Trim() == "Casehistory" ? "Please enter case history." : message;
            message = message.ToString().Trim() == "RequestStatus" ? "Select request status to save!" : message;
            message = message.ToString().Trim() == "ServiceSubGroup" ? "Select a service sub-group" : message;
            message = message.ToString().Trim() == "Labresultcount" ? "Please enter atleast one result value to update." : message;
            message = message.ToString().Trim() == "Labtemplate" ? "Please select report template to print the report." : message;
            message = message.ToString().Trim() == "LabtemplateType" ? "Please select report template to save the report." : message;
            message = message.ToString().Trim() == "Salutation" ? "Please select salutation." : message;
            message = message.ToString().Trim() == "Careof" ? "Please enter careof." : message;
            message = message.ToString().Trim() == "Age" ? "Please enter age." : message;
            message = message.ToString().Trim() == "Relationship" ? "Please enter relationship." : message;
            message = message.ToString().Trim() == "District" ? "Please select district." : message;
            message = message.ToString().Trim() == "ContactNumber" ? "Please enter contact number." : message;
            message = message.ToString().Trim() == "PatientCategory" ? "Please select patient category." : message;
            message = message.ToString().Trim() == "TPAcompnay" ? "Please select company." : message;
            message = message.ToString().Trim() == "Fingerprint" ? "Please scan finger print." : message;
            message = message.ToString().Trim() == "RoleDelete" ? "The role is already assigned." : message;
            message = message.ToString().Trim() == "Invoicenumber" ? "Please enter invoice number." : message;
            message = message.ToString().Trim() == "Chequenumber" ? "Please enter cheque number or UTR number." : message;
            message = message.ToString().Trim() == "samplerecvstatus" ? "Please receive the  collected sample." : message;
            message = message.ToString().Trim() == "Deviceinitiate" ? "Please initiate the device." : message;
            message = message.ToString().Trim() == "BankName" ? "Please select bank." : message;
            message = message.ToString().Trim() == "MTrecivdtime" ? "Please update received time." : message;
            message = message.ToString().Trim() == "OPnumber" ? "Please generate OPD bill." : message;
            message = message.ToString().Trim() == "HospitalShare" ? "Please enter hospital share." : message;
            message = message.ToString().Trim() == "ConsultantShare" ? "Please enter consultant share." : message;
            message = message.ToString().Trim() == "ReportingShare" ? "Please enter reporting share." : message;
            message = message.ToString().Trim() == "Share" ? "Please enter correct share." : message;
            message = message.ToString().Trim() == "MsbType" ? "Please select MSB type." : message;
            message = message.ToString().Trim() == "CustomDiscount" ? "Discount request cannot be done!" : message;
            message = message.ToString().Trim() == "Photo" ? "Employee signature canot be larger than 200 KB!" : message;
            message = message.ToString().Trim() == "Signature" ? "Employee photo canot be larger than 200 KB!" : message;
            message = message.ToString().Trim() == "OPnumber" ? "Please enter opnumber." : message;
            message = message.ToString().Trim() == "informhk" ? "Please inform housekeeing." : message;
            message = message.ToString().Trim() == "informward" ? "Please inform ward." : message;
            message = message.ToString().Trim() == "DocumentType" ? "Please select document type." : message;
            message = message.ToString().Trim() == "Tittle" ? "Please enter document title." : message;
            message = message.ToString().Trim() == "AccountClosed" ? "Account has been closed for this bill." : message;
            message = message.ToString().Trim() == "Dependent" ? "Please select dependent." : message;
            message = message.ToString().Trim() == "ServiceCategory" ? "Please select service category." : message;
            message = message.ToString().Trim() == "Dueresponsible" ? "Please enter responsible employee." : message;
            message = message.ToString().Trim() == "DependentFile" ? "Please browse dependent document." : message;
            message = message.ToString().Trim() == "EmpFile" ? "Please browse employee document." : message;
            message = message.ToString().Trim() == "AddDoc" ? "Please add employee document to file list." : message;
            message = message.ToString().Trim() == "AddDependentDoc" ? "Please add dependent document to file list." : message;
            message = message.ToString().Trim() == "Depositamount" ? "Please enter deposit amount." : message;
            message = message.ToString().Trim() == "Particulars" ? "Please enter particular." : message;
            message = message.ToString().Trim() == "Refundamount" ? "Please enter refund amount." : message;
            message = message.ToString().Trim() == "Verifyrefund" ? "Please verify refund amount." : message;
            message = message.ToString().Trim() == "Change" ? "Successfully released the bed." : message;
            message = message.ToString().Trim() == "Alreadyoccupy" ? "Already occupied by another patient." : message;
            message = message.ToString().Trim() == "Admbedcount" ? "Please select only one bed" : message;
            message = message.ToString().Trim() == "BedCount" ? "You have to release one of the currently occupied bed. One patient could not occupy more than three bed." : message;
            message = message.ToString().Trim() == "NoDiscount" ? "No amount to send request" : message;
            message = message.ToString().Trim() == "ExceedAmount" ? "Paid amount cannot exceed payable amount!" : message;
            message = message.ToString().Trim() == "Admitted" ? "Admission done successfully." : message;
            message = message.ToString().Trim() == "DuplicateOtregd" ? "Already done the registration." : message;
            message = message.ToString().Trim() == "Procedure" ? "Please enter procedure." : message;
            message = message.ToString().Trim() == "Anaesthesiatype" ? "Please enter anaesthesia type." : message;
            message = message.ToString().Trim() == "Relative" ? "Please enter patient relative name." : message;
            message = message.ToString().Trim() == "aspx" ? "Please enter .aspx file only." : message;
            message = message.ToString().Trim() == "role" ? "Please select a employee role." : message;
            message = message.ToString().Trim() == "settlementmode" ? "Please select settlement mode." : message;
            message = message.ToString().Trim() == "WadrRecievd" ? "Please receive the patient to the ward then you can transfer the bed." : message;
            message = message.ToString().Trim() == "Admissioncancel" ? "Amdission could not be cancel. IP services are already recorded. You have to discharge the patient. " : message;
            message = message.ToString().Trim() == "SurgeonShare" ? "Please enter correct surgeon share." : message;
            message = message.ToString().Trim() == "AnasthesShare" ? "Please enter correct anaesthestic share." : message;
            message = message.ToString().Trim() == "OTcancel" ? "Operation is already done. You can not cancel." : message;
            message = message.ToString().Trim() == "OTpayment" ? "OT payment is already done. You can not edit the details." : message;
            message = message.ToString().Trim() == "Procedurecount" ? "You can add only one procedure." : message;
            message = message.ToString().Trim() == "Doctorpay" ? "Successfully done the doctor payment." : message;
            message = message.ToString().Trim() == "DuePayable" ? "There is no any payable services for this doctor." : message;
            message = message.ToString().Trim() == "consent" ? "Patient has not taken consent." : message;
            message = message.ToString().Trim() == "consentType" ? "Please select consent Type." : message;
            message = message.ToString().Trim() == "receivable" ? "Please select IsReceivable Type." : message;
            message = message.ToString().Trim() == "mainsurgeon" ? "Please check one main surgeon." : message;
            message = message.ToString().Trim() == "chkwardrecd" ? "Please receive the patient to the ward  then you can enter the services ." : message;
            message = message.ToString().Trim() == "otcount" ? "Please pay for only one procedure." : message;
            message = message.ToString().Trim() == "discharge" ? "Patient is already been discharge." : message;
            message = message.ToString().Trim() == "doubleclick" ? "An attempt was made to submit this form more than once; this extra attempt will be ignored." : message;
            message = message.ToString().Trim() == "SRack" ? "Please select a rack." : message;
            message = message.ToString().Trim() == "SLooks" ? "Please select a looks Alike." : message;
            message = message.ToString().Trim() == "Ssound" ? "Please select a sound Alike." : message;
            message = message.ToString().Trim() == "SubRack" ? "Please select a sub rack." : message;
            message = message.ToString().Trim() == "approvedqty" ? "Approved quantity cannot be greater than indent quantity." : message;
            message = message.ToString().Trim() == "Rejection" ? "Please enter remarks." : message;
            message = message.ToString().Trim() == "Alreadyapprove" ? "Already approved for this indent number." : message;
            message = message.ToString().Trim() == "NursingStation" ? "Please select nursing station." : message;
            message = message.ToString().Trim() == "Ward" ? "Please select ward." : message;
            message = message.ToString().Trim() == "Nurse" ? "Please select staff nurse." : message;
            message = message.ToString().Trim() == "Alreadyassign" ? " Already added to one of the station." : message;
            message = message.ToString().Trim() == "GenStock" ? "Please select stock type." : message;
            message = message.ToString().Trim() == "GenSubStock" ? "Please select sub stock type." : message;
            message = message.ToString().Trim() == "StockQty" ? "Please enter request quantity." : message;
            message = message.ToString().Trim() == "DeleteIndent" ? "Indent is already processed.So you could not delete." : message;
            message = message.ToString().Trim() == "UseRecord" ? "Qty used cannot be greater than available stock." : message;
            message = message.ToString().Trim() == "NotAvail" ? "Item not availbale" : message;
            message = message.ToString().Trim() == "Supervisor" ? "Please select Supervisor." : message;
            message = message.ToString().Trim() == "Astnusingsuperitenednt" ? "Please select Asst. Nusrsing Superitendant." : message;
            message = message.ToString().Trim() == "VerificationStatus" ? "Please select verification status." : message;
            message = message.ToString().Trim() == "StockStatus" ? "Please select stock status." : message;
            message = message.ToString().Trim() == "FinancialYear" ? "Please select Financial Year." : message;
            message = message.ToString().Trim() == "Months" ? "Please select Month." : message;
            message = message.ToString().Trim() == "StockQty" ? "Please enter condemn quantity." : message;
            message = message.ToString().Trim() == "CondemnOver" ? "Condemn quantity can not be greater than Available quantity." : message;
            message = message.ToString().Trim() == "OverStockTransfer" ? "Transter quantity can not be greater than Available quantity." : message;
            message = message.ToString().Trim() == "InterTransferTo" ? "Please select transfer to." : message;
            message = message.ToString().Trim() == "StockCannotDelete" ? "The stock that you have transfer has already started use, So, this transfer stock cannot be delete," : message;
            message = message.ToString().Trim() == "ReceiptBlank" ? "Receipt number cannot be blank.," : message;
            message = message.ToString().Trim() == "PaidAmount" ? "Please enter paid amount." : message;
            message = message.ToString().Trim() == "Supplier" ? "Please enter Supplier." : message;
            message = message.ToString().Trim() == "mfgcompany" ? "Please select menufacturing company." : message;
            message = message.ToString().Trim() == "producCtg" ? "Please select item category." : message;
            message = message.ToString().Trim() == "BedPost" ? "Successfully posted the bed." : message;
            message = message.ToString().Trim() == "ABedPost" ? "Already posted the bed." : message;
            message = message.ToString().Trim() == "BedPostEnable" ? "You do not have the ridhts." : message;
            message = message.ToString().Trim() == "VED" ? "Please select VED category." : message;
            message = message.ToString().Trim() == "Source" ? "Please select patient source." : message;
            message = message.ToString().Trim() == "ReferBy" ? "Please select patient Refer by." : message;
            message = message.ToString().Trim() == "bookedOTSchedule" ? "This OT time have already scheduled ." : message;
            message = message.ToString().Trim() == "GreaterFrequency" ? "Medication cannot be more than drug frquency. ." : message;
            message = message.ToString().Trim() == "ValidTime" ? "Please enter valid time." : message;
            message = message.ToString().Trim() == "ExcessTime" ? "Time is excess from system time. Please enter valid time." : message;
            message = message.ToString().Trim() == "LeaveApproveEnable" ? "You do not have the rights to approve leave request." : message;
            message = message.ToString().Trim() == "LeaveRequestEnable" ? "You do not have the rights to request leave." : message;
            message = message.ToString().Trim() == "LeaveRejectEnable" ? "You do not have the rights to reject leave request." : message;
            message = message.ToString().Trim() == "ShiftType" ? "Please select shift type ." : message;
            message = message.ToString().Trim() == "SummerstartTime" ? "Please enter summer start time ." : message;
            message = message.ToString().Trim() == "SummerendTime" ? "Please enter summer end time ." : message;
            message = message.ToString().Trim() == "Summerinrelaxation" ? "Please enter summer in relaxation time ." : message;
            message = message.ToString().Trim() == "Summeroutrelaxation" ? "Please enter summer out relaxation time ." : message;
            message = message.ToString().Trim() == "Rosternextday" ? "Sorry, Cannot have multiple next day ." : message;
            message = message.ToString().Trim() == "WinterstartTime" ? "Please enter winter start time ." : message;
            message = message.ToString().Trim() == "WinterendTime" ? "Please enter winter end time ." : message;
            message = message.ToString().Trim() == "Winterinrelaxation" ? "Please enter winter in relaxation time ." : message;
            message = message.ToString().Trim() == "Winteroutrelaxation" ? "Please enter winter out relaxation time ." : message;
            message = message.ToString().Trim() == "NurseShift" ? "Please select Nurse Shift." : message;
            message = message.ToString().Trim() == "PatientDischarge" ? "Patient is already discharged." : message;
            message = message.ToString().Trim() == "Custommer" ? "Please enter customer name." : message;
            message = message.ToString().Trim() == "Reqsent" ? "Request has sent." : message;
            message = message.ToString().Trim() == "Paid" ? "Paid Amount cannot be blank." : message;
            message = message.ToString().Trim() == "IndentStus" ? "Please select indent status." : message;
            message = message.ToString().Trim() == "NoUnit" ? "Please enter number of unit." : message;
            message = message.ToString().Trim() == "UpperLimit" ? "Lower limit can not be greater than upper limit." : message;
            message = message.ToString().Trim() == "PHRbillStatus" ? "Pharmacy billing is not done yet. Please coordinate with pharmacy counter and then try again..." : message;
			message = message.ToString().Trim() == "PHRLedger" ? "Please select account." : message;
            message = message.ToString().Trim() == "Dueamount" ? "Please enter correct responsible due amount." : message;
            message = message.ToString().Trim() == "Respamount" ? "Please enter amount for the added responsible person." : message;
            message = message.ToString().Trim() == "HSNCode" ? "Please enter HSN/SAC Code." : message;
            message = message.ToString().Trim() == "PhrAccessLimit" ? "This patient has reach due limit, item issue can be permit after due payment." : message;
            message = message.ToString().Trim() == "RunnerName" ? "Please select runner name." : message;
            message = message.ToString().Trim() == "Collectioncentre" ? "Please select collection centre." : message;
            message = message.ToString().Trim() == "test" ? "Please enter test." : message;
            message = message.ToString().Trim() == "SelectReferal" ? "Please Select Correct Referal Name." : message;
            message = message.ToString().Trim() == "SourceType" ? "Please Select Source Type." : message;
            message = message.ToString().Trim() == "SourceName" ? "Please Select Correct Source Name." : message;
            message = message.ToString().Trim() == "SourceAddress" ? "Please enter address." : message;
            message = message.ToString().Trim() == "TestType" ? "Please Select Test Type." : message;
            message = message.ToString().Trim() == "ElementOrderNo" ? "Please Enter Order No to Insert the Parameter from this Element" : message;
            message = message.ToString().Trim() == "DuplicateParam" ? "Element Already Exist" : message;
            message = message.ToString().Trim() == "TestCode" ? "Please enter Testcode" : message;
            message = message.ToString().Trim() == "BiometricNo" ? "Please enter Biometric No." : message;
            lbl.Visible = true;
            lbl.Text = message;
            lbl.CssClass = msgType == 1 ? "SucessAlert" : "FailAlert";
            return;
        }
        internal static void ShowMessage(object message, string v1, int v2)
        {
            throw new NotImplementedException();
        }
    }
}
