using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

namespace Mediqura.CommonData.Common
{
    public enum LookupName
    {
        [EnumMember]
        FinancialYearID,
        [EnumMember]
        Roles,
        [EnumMember]
        Gender,
        [EnumMember]
        PaymentMode,
        [EnumMember]
        Employee,
        [EnumMember]
        Nationality,
        [EnumMember]
        Marital,
        [EnumMember]
        Salutation,
        [EnumMember]
        Country,
        [EnumMember]
        State,
        [EnumMember]
        District,
        [EnumMember]
        Relationship,
        [EnumMember]
        Religion,
        [EnumMember]
        PatientType,
        [EnumMember]
        AllPatientType,
        [EnumMember]
        MSbPatientType,
        [EnumMember]
        Profession,
        [EnumMember]
        ServiceType,
        [EnumMember]
        Designation,
        [EnumMember]
        Department,
        [EnumMember]
        EmployeeType,
        [EnumMember]
        OPDepartment,
        [EnumMember]
        CollectedBy,
        [EnumMember]
        OPServiceType,
        [EnumMember]
        Referal,
        [EnumMember]
        OPservices,
        [EnumMember]
        Groups,
        [EnumMember]
        GenGroups,
        [EnumMember]
        SubGroups,
        [EnumMember]
        LabGroups,
        [EnumMember]
        LabGroup,
        [EnumMember]
        LabSubGroups,
        [EnumMember]
        ProfileGroups,
        [EnumMember]
        OutsiderPatientType,
        [EnumMember]
        DischargeStatus,
        [EnumMember]
        IPDepartment,
        [EnumMember]
        Doctor,
        [EnumMember]
        PaidDoctor,
        [EnumMember]
        BlockType,
        [EnumMember]
        FloorType,
        [EnumMember]
        WardType,
        [EnumMember]
        IPDWardType,
        [EnumMember]
        Supplier,
        [EnumMember]
        StockType,
        [EnumMember]
        GenStockType,
        [EnumMember]
        HandOver,
        [EnumMember]
        TestCenter,
        [EnumMember]
        Urgency,
        [EnumMember]
        SmpleType,
        [EnumMember]
        OT_statusType,
        [EnumMember]
        Anaesthesia,
        [EnumMember]
        AnaesthesiaEmpList,
        [EnumMember]
        ParentSiteMap,
        [EnumMember]
        DoctorType,
        [EnumMember]
        month,
        [EnumMember]
        BelowCurMonth,
        [EnumMember]
        Year,
        [EnumMember]
        OPDoctorType,
        [EnumMember]
        StockRecievedBy,
        [EnumMember]
        StockStatus,
        [EnumMember]
        NurseType,
        [EnumMember]
        week,
        [EnumMember]
        Mfgcompany,
        [EnumMember]
        SupplierID,
        [EnumMember]
        Stocktoissue,
        [EnumMember]
        ItemHandedTo,
        [EnumMember]
        IssuedBy,
        [EnumMember]
        ReturnBy,
        [EnumMember]
        DiscountBy,
        [EnumMember]
        PHRcollectedBy,
        [EnumMember]
        IPServiceType,
        [EnumMember]
        LABServiceType,
        [EnumMember]
        PHRServiceType,
        [EnumMember]
        OTroles,
        [EnumMember]
        OTtheater,
        [EnumMember]
        OTcase,
        [EnumMember]
        OTdoctor,
        [EnumMember]
        SubStockType,
        [EnumMember]
        TestName,
        [EnumMember]
        OTServiceType,
        [EnumMember]
        CodeRange,
        [EnumMember]
        Company,
        [EnumMember]
        Package,
        [EnumMember]
        bankName,
        [EnumMember]
        requestType,
        [EnumMember]
        Unit,
        [EnumMember]
        AgeRange,
        [EnumMember]
        RowType,
        [EnumMember]
        MachineName,
        [EnumMember]
        IndentStatus,
        [EnumMember]
        LabStatus,
        [EnumMember]
        ApprovedBy,
        [EnumMember]
        TPAList,
        [EnumMember]
        LabDevStatus,
        [EnumMember]
        LabDevName,
        [EnumMember]
        AccountGroup,
        [EnumMember]
        AccountGroupNature,
        [EnumMember]
        AccountLedger,
        [EnumMember]
        Reagent,
        [EnumMember]
        EmergencyDoc,
        [EnumMember]
        EmerService,
        [EnumMember]
        TransactionType,
        [EnumMember]
        Method,
        [EnumMember]
        EmrgPHRService,
        [EnumMember]
        OPEmerServiceType,
        [EnumMember]
        OPEmerDoctorType,
        [EnumMember]
        IPDDoctorRoundServiceType,
        [EnumMember]
        MinorOTServiceType,
        [EnumMember]
        MajorOTServiceType,
        [EnumMember]
        EmpGrade,
        [EnumMember]
        MsbRelation,
        [EnumMember]
        StaffCategory,
        [EnumMember]
        Caste,
        [EnumMember]
        BloodGroup,
        [EnumMember]
        EmrgService,
        [EnumMember]
        DisType,
        [EnumMember]
        CommonGroups,
        [EnumMember]
        SubServiceType,
        [EnumMember]
        PhrUnit,
        [EnumMember]
        GENPhrUnit,
        [EnumMember]
        Container,
        [EnumMember]
        InvestigationGroup,
        [EnumMember]
        DiscountStatus,
        [EnumMember]
        DiscountReqBy,
        [EnumMember]
        LabGroupForEndoAndRadio,
        [EnumMember]
        MOTOTHGroups,
        [EnumMember]
        LabTech,
        [EnumMember]
        Labconsultant,
        [EnumMember]
        LabSubGroup,
        [EnumMember]
        PHRusers,
        [EnumMember]
        Rack,
        [EnumMember]
        PatientCatagory,
        [EnumMember]
        SubRack,
        [EnumMember]
        TaxDoctors,
        [EnumMember]
        LabServiceSubGroup,
        [EnumMember]
        PathologyDoctor,
        [EnumMember]
        LabTemplate,
        [EnumMember]
        Branch,
        [EnumMember]
        CommonGroupAll,
        [EnumMember]
        LabGroupAll,
        [EnumMember]
        TransDeft,
        [EnumMember]
        PaymentType,
        [EnumMember]
        OPLabPatientcategory,
        [EnumMember]
        MsbBenifit,
        [EnumMember]
        SubDiscount,
        [EnumMember]
        TPAOnly,
        [EnumMember]
        WithoutTPA,
        [EnumMember]
        Nurse,
        [EnumMember]
        DuePatientType,
        [EnumMember]
        GetAllInsurance,
        [EnumMember]
        EmpDocType,
        [EnumMember]
        IPbeddetails,
        [EnumMember]
        ConsentType,
        [EnumMember]
        NurseStation,
        [EnumMember]
        StationType,
        [EnumMember]
        OTcases,
        [EnumMember]
        DashBoardUrl,
        [EnumMember]
        CollectionLedger,
        [EnumMember]
        CollectionByAccount,
        [EnumMember]
        OTpayabledoctors,
        [EnumMember]
        Radiologist,
        [EnumMember]
        FrontDeskUser,
        [EnumMember]
        CommonGroup,
        [EnumMember]
        StoreEmp,
        [EnumMember]
        GenSupplier,
        [EnumMember]
        IncomeTransaction,
        [EnumMember]
        Services,
        [EnumMember]
        GEN_Rack,
        [EnumMember]
        GEN_sounds,
        [EnumMember]
        GEN_looks,
        [EnumMember]
        PHR_sounds,
        [EnumMember]
        PHR_looks,
        [EnumMember]
        Gen_Dept,
        [EnumMember]
        DueEmployee,
        [EnumMember]
        EndoscopyDoctor,
        [EnumMember]
        NurseGenStock,
        [EnumMember]
        HeaderType,
        [EnumMember]
        Supervisor,
        [EnumMember]
        Superintendent,
        [EnumMember]
        OTStatusID,
        [EnumMember]
        Hour,
        [EnumMember]
        Minute,
        [EnumMember]
        PAC,
        [EnumMember]
        Route,
        [EnumMember]
        GCSEyeOpening,
        [EnumMember]
        GCSMortorResponse,
        [EnumMember]
        GCSVerval,
        [EnumMember]
        RightPupilReaction,
        [EnumMember]
        LeftPupilReaction,
        [EnumMember]
        Leavetype,
        [EnumMember]
        season,
        [EnumMember]
        Roster,
        [EnumMember]
        ShiftType,
        [EnumMember]
        LeaveApprover,
        [EnumMember]
        MedHandOver,
        [EnumMember]
        CustomerType,
        [EnumMember]
        CollectionByPHRUser,
        [EnumMember]
        PHRAccountGroup,
        [EnumMember]
        PHRPaymentType,
        [EnumMember]
        PHRtransactionType,
        [EnumMember]
        PHRAccountLedger,
        [EnumMember]
        MenuHeader,
        [EnumMember]
        OPpayoutGroup,
        [EnumMember]
        RunnerList,
        [EnumMember]
        VisitTo,
        [EnumMember]
        Microbiologist,
        [EnumMember]
        CulLabTemplate,
        [EnumMember]
        AntiSense,
        [EnumMember]
        ReferalType,
        [EnumMember]
        LabAccessioner
    }
}
